### ISSUE TITLE
Before submit dynamic action doesn't wait for club uploading before processing

### ISSUE THREAD

**Issue by yotamcons** [RonnyWeiss/APEX-CLOB-Load-2#1]
Hey Ronny,
first of all thank you for all the beautiful plugins you provide.

I installed CLOB load 2 in my app (apex 19.1 over oracle DB 19c), and created a "before submit" dynamic action, with a "submit" button. My page also has page processes that were meant to work with an uploaded collection. When testing the submission of the page with different sizes of CLOBs I sometime got a bug when an *older clob data* was saved.
I first tried to delete the collection after the saving process, but then I got a "collection does not exist" error.

After looking into this using plsql logging in different steps I found out the the "before submit" dynamic actions are only waiting for the result on that specific dynamic action thread, but the Apex processes start running *even though "wait for result" is selected in the action*.

my work around was to move the submission of the page to a dynamic action which fires "onClick" of the button, but has the APEX-CLOB-Load-2 action beforehand

**Comment by RonnyWeiss** [comment]
When you have problems with before submit event then please fire the upload on click of button e.g. and in this dynamic action you can fire after upload the submit of the page. 

I haven't quite debugged yet why before page submit sometimes comes too late. It feels like it's how you submitted the page:

Page Attribute: 

Reload on Submit

Select when the page should be reloaded following a page submission.
